// Auto-generated by scripts/generate-design-candidates.mjs
export interface DesignAsset {
  id: string;
  sourceIdentifier: string;
  localPath: string;
  originalPackPath: string;
  originalSha256: string;
  derivativeSha256: string;
  width: number;
  height: number;
  status: 'approved-brand-asset' | 'unverified-unlisted-candidate' | 'needs-source-verification' | 'needs-source-verification-high-risk';
  allowedUses: string[];
  prohibitedUses: string[];
  recommendedPlacement: string;
}

export const DESIGN_ASSET_REGISTRY: Record<string, DesignAsset> = {
  "BRAND-001": {
    "id": "BRAND-001",
    "sourceIdentifier": "1Yf3_PhRPO8uv1WuRdkPGUrIK9VAhu6IG",
    "localPath": "/brand/sky-logo-illustrated-badge.jpg",
    "originalPackPath": "01-brand/approved/sky-logo-illustrated-badge.jpg",
    "originalSha256": "615fe916e4db10a85da32e5674d5504c08c5452f2ed1aed405a30a88a2856856",
    "derivativeSha256": "615fe916e4db10a85da32e5674d5504c08c5452f2ed1aed405a30a88a2856856",
    "width": 926,
    "height": 845,
    "status": "approved-brand-asset",
    "allowedUses": [
      "website branding",
      "navigation",
      "estimate intake",
      "social link previews",
      "print",
      "bids"
    ],
    "prohibitedUses": [
      "completed-project proof",
      "unapproved recoloring",
      "third-party redistribution"
    ],
    "recommendedPlacement": "Canonical logo only. Preserve proportions and clear space."
  },
  "CANDIDATE-BRANDED-EQUIPMENT": {
    "id": "CANDIDATE-BRANDED-EQUIPMENT",
    "sourceIdentifier": "1LACDjxXxu38MAeskoLpYP8eW3ewlnjWG",
    "localPath": "/design-lab/candidates/branded-equipment.webp",
    "originalPackPath": "01-brand/unverified-candidates/branded-equipment.png",
    "originalSha256": "8b2809e7d3e8dbcc72872e305c80cbf452e06ef7baba5a8d46d972697ac09d9d",
    "derivativeSha256": "ea4a2a6e358898cc2499d6d1ca8f2795210af61db1110df491fee5fe695212e6",
    "width": 1440,
    "height": 958,
    "status": "unverified-unlisted-candidate",
    "allowedUses": [
      "internal design concepts",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "production proof",
      "case study",
      "Google Business Profile",
      "ad claim"
    ],
    "recommendedPlacement": "Possible owner/equipment or brand-documentary visual after source verification."
  },
  "CANDIDATE-INTERIOR-LIVING-ROOM": {
    "id": "CANDIDATE-INTERIOR-LIVING-ROOM",
    "sourceIdentifier": "1fC3k1dNKj4d137Pv5zir1LHQcbrp0ITo",
    "localPath": "/design-lab/candidates/interior-living-room.webp",
    "originalPackPath": "02-portfolio-candidates/residential/interior-living-room.png",
    "originalSha256": "897cd1eecd2307d275dacad11025a88f9a70492085dc458f2b505d4f64e4857f",
    "derivativeSha256": "1b687a5ac91d6e8c8ec41163099c2ca4caeb0d356f2ce95e469e85d6b4e10f00",
    "width": 1440,
    "height": 1080,
    "status": "unverified-unlisted-candidate",
    "allowedUses": [
      "internal design concepts",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "production project proof",
      "case study",
      "testimonial support",
      "GBP"
    ],
    "recommendedPlacement": "Potential finished residential visual; verify project ownership and permission."
  },
  "CANDIDATE-INTERIOR-KITCHEN": {
    "id": "CANDIDATE-INTERIOR-KITCHEN",
    "sourceIdentifier": "152Vrn8n-v1suPYD_TwmaOPnWaHpb9iya",
    "localPath": "/design-lab/candidates/interior-kitchen.webp",
    "originalPackPath": "02-portfolio-candidates/residential/interior-kitchen.png",
    "originalSha256": "4baf1a35b97dea74679340c78c71d4cc940c79f42e5b05b1fb517034bcb22762",
    "derivativeSha256": "7bf7e06bfd3cd4b57481b0fc8afa4301cd2f612e43fd670304f9c9e7d4072b15",
    "width": 1440,
    "height": 960,
    "status": "unverified-unlisted-candidate",
    "allowedUses": [
      "internal design concepts",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "production project proof",
      "case study",
      "testimonial support",
      "GBP"
    ],
    "recommendedPlacement": "Potential residential finished-result visual; verify provenance."
  },
  "CANDIDATE-INTERIOR-BEDROOM-BEFORE-AFTER": {
    "id": "CANDIDATE-INTERIOR-BEDROOM-BEFORE-AFTER",
    "sourceIdentifier": "1EKHWVFLNddDWX74PggtQvXPc-JCR6ZSf",
    "localPath": "/design-lab/candidates/interior-bedroom-before-after.webp",
    "originalPackPath": "02-portfolio-candidates/residential/interior-bedroom-before-after.png",
    "originalSha256": "00b6d0a662fbb43878a89747c8089422b136866f6efb851f9a38e312426ad1b0",
    "derivativeSha256": "a62f560c1a0ce85877cd99597d746a2a2910683783aca02a17770acc7c571766",
    "width": 1440,
    "height": 960,
    "status": "unverified-unlisted-candidate",
    "allowedUses": [
      "internal design concepts",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "production before/after claim",
      "case study",
      "testimonial support",
      "GBP"
    ],
    "recommendedPlacement": "Best candidate for the signature before/after interaction once verified."
  },
  "PHOTO-002": {
    "id": "PHOTO-002",
    "sourceIdentifier": "1U_YuMYiPRPnRwqghKFpLqiuhLBo32J8P",
    "localPath": "/design-lab/candidates/interior-action.webp",
    "originalPackPath": "02-portfolio-candidates/process/interior-action.png",
    "originalSha256": "58d26f59af4249fe16f00b65515bf397b6aaabdea8e9815b9f72684647412089",
    "derivativeSha256": "d13c426e5867cd5f3ddfb256e6db533fdc5836fe9b6a8d5c4702bd0f40d2699b",
    "width": 1402,
    "height": 1122,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "completed-customer proof",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Potential owner/process action image after identity, project, and release verification."
  },
  "PHOTO-007": {
    "id": "PHOTO-007",
    "sourceIdentifier": "1nQa5pTXnZ-A5lKmVYkutJn-Ea-KLBJZz",
    "localPath": "/design-lab/candidates/surface-preparation-closeup.webp",
    "originalPackPath": "02-portfolio-candidates/process/surface-preparation-closeup.png",
    "originalSha256": "b6c3bb86bbf09ee184dbcd6c897c690d0f206f71a3232fe70602ed46a0d0613d",
    "derivativeSha256": "3891b5772bb775be1e0e85a1981e5787adfad5f2362e6912888d209d13cdb9d6",
    "width": 1402,
    "height": 1122,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "completed-customer proof",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Strong candidate for the preparation-detail story after verification."
  },
  "PHOTO-004": {
    "id": "PHOTO-004",
    "sourceIdentifier": "1pFNnt2I7QzM6CSbR-WHO3re8zlk08bNA",
    "localPath": "/design-lab/candidates/commercial-finished.webp",
    "originalPackPath": "02-portfolio-candidates/commercial/commercial-finished.png",
    "originalSha256": "e98c141241c9c50d7d21e9f58a01c1a2d26ad554da70952e98e3ed593f840e9f",
    "derivativeSha256": "14f520127f3dd8b58553184141dad03ef3894a9547a0e4655bee8c11b3c58dcb",
    "width": 1440,
    "height": 1080,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "completed-customer proof",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Potential commercial finished-result visual after project linkage."
  },
  "PHOTO-006": {
    "id": "PHOTO-006",
    "sourceIdentifier": "18Dpo93-ktOBrKlWRtpyhGnWwzimJk0xn",
    "localPath": "/design-lab/candidates/commercial-action.webp",
    "originalPackPath": "02-portfolio-candidates/commercial/commercial-action.png",
    "originalSha256": "4a78b3a9b896b712d99c4cbbc13414642561fdd400d82b6264e5509d58bb669a",
    "derivativeSha256": "b3f79b812869beacfe626fa856f084a1ceb0c53e8e8de1b1e9445dcd4897bf21",
    "width": 1440,
    "height": 1080,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "completed-customer proof",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Possible commercial action/process image after worker and job ownership verification."
  },
  "PHOTO-005": {
    "id": "PHOTO-005",
    "sourceIdentifier": "1MaM-bybuNt9sR6A2OtjlYaEFBzR52oXV",
    "localPath": "/design-lab/candidates/parking-lot-striping.webp",
    "originalPackPath": "02-portfolio-candidates/public-sector/parking-lot-striping.png",
    "originalSha256": "8ddfe4dde1b3588ac25c41a6d1bfc6d8871b6211687a65e53872041e672f3ab3",
    "derivativeSha256": "f56badcb116b7977240ca697ecd6bd9c0f99fd85b9edd01be3224cbd5b08ca42",
    "width": 1440,
    "height": 1080,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "municipal claim",
      "government-client claim",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Public/commercial capability concept only; never imply a municipal award without records."
  },
  "PHOTO-003": {
    "id": "PHOTO-003",
    "sourceIdentifier": "1GOvMxTxJe-wp_4bAn_h2t9v4eo8_5I6x",
    "localPath": "/design-lab/candidates/light-pole-painting.webp",
    "originalPackPath": "02-portfolio-candidates/public-sector/light-pole-painting.png",
    "originalSha256": "0c57b6646d1adcf0448ac6bedf1eb61087cdba6a1fe2be602c12875963ab7a1c",
    "derivativeSha256": "45e0ea7d0d8751810d6ed41a47d6c59c2bb29ed4d1d6a71da26c2fdf874fde1b",
    "width": 1402,
    "height": 1122,
    "status": "needs-source-verification-high-risk",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "city contract claim",
      "award claim",
      "completed public project claim",
      "GBP"
    ],
    "recommendedPlacement": "High-impact public-asset visual, but high claim risk. Verify award/project documentation first."
  },
  "PHOTO-001": {
    "id": "PHOTO-001",
    "sourceIdentifier": "1PZv2s_8s7uRL0MDngmURl5N7nSPcfJAm",
    "localPath": "/design-lab/candidates/exterior-action-with-logo.webp",
    "originalPackPath": "02-portfolio-candidates/exterior/exterior-action-with-logo.png",
    "originalSha256": "4dff71423b6e2dbef24c2d8110a95e689dda88bed36b687c23c3d3eed2a963d3",
    "derivativeSha256": "286f5b50b1ab910018c68cb959c554ecd2a96eb612cb11ee889d66c732bb4470",
    "width": 1402,
    "height": 1122,
    "status": "needs-source-verification",
    "allowedUses": [
      "marketing layouts only until verified",
      "protected design-lab previews"
    ],
    "prohibitedUses": [
      "completed-customer proof",
      "GBP",
      "public case study"
    ],
    "recommendedPlacement": "Potential exterior action hero or project-story visual after verification."
  }
};

export function isCandidateAllowedInCurrentEnv(): boolean {
  if (typeof window !== 'undefined') {
    // Client-side evaluation
    return process.env.NEXT_PUBLIC_SIGNATURE_DESIGN_PREVIEW === 'true';
  }
  // Server-side evaluation
  const isProduction = process.env.VERCEL_ENV === 'production' || process.env.NODE_ENV === 'production';
  const previewEnabled = process.env.NEXT_PUBLIC_SIGNATURE_DESIGN_PREVIEW === 'true';
  return !isProduction && previewEnabled;
}

export function getSafeAssetPath(assetId: string, fallbackPath = '/brand/sky-logo-illustrated-badge.jpg'): string {
  const asset = DESIGN_ASSET_REGISTRY[assetId];
  if (!asset) return fallbackPath;
  if (asset.status === 'approved-brand-asset') return asset.localPath;
  if (isCandidateAllowedInCurrentEnv()) return asset.localPath;
  return fallbackPath;
}
